# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  brainfuck_config = debug

else ifeq ($(config),release)
  brainfuck_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := brainfuck

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

brainfuck:
ifneq (,$(brainfuck_config))
	@echo "==== Building brainfuck ($(brainfuck_config)) ===="
	@${MAKE} --no-print-directory -C . -f brainfuck.make config=$(brainfuck_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f brainfuck.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   brainfuck"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"